### ISSUE TITLE
Violation of CC-BY-NC-ND 4.0

### ISSUE THREAD

**Issue by smintf** [spyderplane6/blooket-hack#1]
This repository violates the Apache-2.0 License, as it violates section 4 subheading REDISTRIBUTION.

**Comment by smintf** [comment]
You may read a copy of the license [here](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by TheRedstoneRadiant** [comment]
OMG

**Comment by Everest187** [comment]
OMG HOW DARE U

**Comment by Everest187** [comment]
BOI DELETE THIS RESP

**Comment by smintf** [comment]
As for whether this can even apply.
It can as its a Derivative Work of [Blooketware/BlooketUI](https://github.com/Blooketware/BlooketUI/)

**Comment by smintf** [comment]
I request you to either provide full credit, put a copy of the license in this repository or take this repository down entirely.

**Comment by smintf** [comment]
I have just relicensed my work to `Creative Commons Attribution-NonCommercial-NoDerivatives 4.0`

**Comment by smintf** [comment]
And again this repository violates the above license. 
Specifically, Section 3 "License Conditions." Subheading Attribution.

**Comment by smintf** [comment]
> I request you to either provide full credit, put a copy of the license in this repository or take this repository down entirely.

Again I request you to provide full credit and link to a copy of the license or take this repository down entirely.
Else I will be forced to take further action.

**Comment by spyderplane6** [comment]
i added a credit sorry i couldn't  to it sooner  if you dont like it just send me a better one for me to just copy and past in to it
